cares_reinforcement_learning/algorithm/TD3.py, example/example_training_loop.py
Add evaluation function and render option
=> evaluation function

cares_reinforcement_learning/algorithm/TD3.py
add eval() and train() lines need for batch normalization
=> add eval() and train() lines

cares_reinforcement_learning/algorithm/DDPG.py, cares_reinforcement_learning/algorithm/DQN.py, cares_reinforcement_learning/algorithm/DoubleDQN.py, cares_reinforcement_learning/algorithm/PPO.py, cares_reinforcement_learning/algorithm/SAC.py, cares_reinforcement_learning/algorithm/TD3.py
=> Refactor all save/load models

cares_reinforcement_learning/algorithm/policy/DDPG.py, cares_reinforcement_learning/algorithm/policy/PPO.py, cares_reinforcement_learning/algorithm/policy/SAC.py, cares_reinforcement_learning/algorithm/policy/TD3.py, cares_reinforcement_learning/algorithm/value/DQN.py, cares_reinforcement_learning/algorithm/value/DoubleDQN.py
Ensure all algorithms return a dictionary
=> 52 algorithm classes return value

.gitignore, cares_reinforcement_learning/algorithm/policy/DDPG.py, cares_reinforcement_learning/algorithm/policy/SAC.py, cares_reinforcement_learning/algorithm/policy/TD3.py, cares_reinforcement_learning/algorithm/value/DQN.py, cares_reinforcement_learning/algorithm/value/DoubleDQN.py
Revert the algorithm part of `train_policy` back to a more readable format. Write to the `info` dictionary at function's end
=> 55 separate info from algorithm

cares_reinforcement_learning/util/Plot.py, cares_reinforcement_learning/util/Record.py, example/example_training_loops.py, example/policy_example.py, example/ppo_example.py, example/value_example.py
Implementation of Record class in _example_training_loops.py_ 
- replace and record all logs from training and evaluation on one csv file (using Record)
- plots dynamically in training (and selected evaluations) 
- saves avg plots for all attributes in csv file 
Changes made to Plot.py:
- commented out line 75 because its causing "AttributeError: no attribute save.csv"
To work on:
=> Dev/record #59

cares_reinforcement_learning/util/Record.py, example/example_training_loops.py
This PR allows the inclusion of a flag that determines whether checkpoint models are saved.
=> feat: add option for saving checkpoint models

cares_reinforcement_learning/util/Plot.py, cares_reinforcement_learning/util/Record.py
Every time we are plotting anything, we create a new figure – this ends up consuming memory.
Instead, this PR writes/rewrites over the same figure and then writes to file– this conserves memory
=> 75 potential memory leak in record

cares_reinforcement_learning/algorithm/policy/DDPG.py, cares_reinforcement_learning/algorithm/policy/PPO.py, cares_reinforcement_learning/algorithm/policy/SAC.py, cares_reinforcement_learning/algorithm/policy/TD3.py, cares_reinforcement_learning/algorithm/value/DQN.py, cares_reinforcement_learning/algorithm/value/DoubleDQN.py, cares_reinforcement_learning/networks/DDPG/Actor.py, cares_reinforcement_learning/networks/DDPG/Critic.py, cares_reinforcement_learning/networks/DQN/network.py, cares_reinforcement_learning/networks/DoubleDQN/network.py, cares_reinforcement_learning/networks/DuelingDQN/Network.py, cares_reinforcement_learning/networks/PPO/Actor.py, cares_reinforcement_learning/networks/PPO/Critic.py, cares_reinforcement_learning/networks/SAC/Actor.py, cares_reinforcement_learning/networks/SAC/Critic.py, cares_reinforcement_learning/networks/TD3/Actor.py, cares_reinforcement_learning/networks/TD3/Critic.py, cares_reinforcement_learning/util/NetworkFactory.py, cares_reinforcement_learning/util/arguement_parser.py
all LR and optimizer moved out
=> LR move out

cares_reinforcement_learning/algorithm/policy/TD3.py, cares_reinforcement_learning/networks/TD3/Actor.py, cares_reinforcement_learning/networks/TD3/Critic.py, cares_reinforcement_learning/util/configurations.py, cares_rl_configs/TD3_algorithm_config.json
TD3 small details were fixed. All the configurations now are based on exactly the same code provided by the TD3 authors. Major changes include network size, new learning rates, and using a single critic for the actor loss.
=> fix td3 to original

cares_reinforcement_learning/util/NetworkFactory.py, tests/test_utils.py
Currently iterates over members and does checks to see if algorithm creation exists.
=> feat: make network factory dynamic

cares_reinforcement_learning/util/configurations.py
Fixes #111 boolean bug by swapping bool to int 0/1
=> RL parser bool to int

.github/workflows/autoformatting.yml, cares_reinforcement_learning/util/helpers.py
Add autoformatting action from pyboy environments.
=> Add autoformatting workflow

cares_reinforcement_learning/algorithm/policy/CTD4.py
Resolve the fusion_variance issue and make the Kalman filter more stable considering the second standard deviation. Additionally a small value is added to avoid having values = 0
=> Resolve fusion_variance issue

cares_reinforcement_learning/algorithm/policy/MAPERSAC.py, cares_reinforcement_learning/algorithm/policy/MAPERTD3.py, cares_reinforcement_learning/algorithm/policy/PERSAC.py, cares_reinforcement_learning/algorithm/policy/PERTD3.py, cares_reinforcement_learning/algorithm/policy/RDSAC.py, cares_reinforcement_learning/algorithm/policy/RDTD3.py, cares_reinforcement_learning/util/configurations.py
If all the training at the lab goes well, then should be able to merge
=> Fix weights tensor conversion

cares_reinforcement_learning/algorithm/policy/LA3PSAC.py, cares_reinforcement_learning/algorithm/policy/LA3PTD3.py, cares_reinforcement_learning/util/configurations.py
=> Fix to LA3P methods

cares_reinforcement_learning/networks/CTD4/distributed_critic.py, cares_reinforcement_learning/networks/CTD4/ensemble_critic.py, cares_reinforcement_learning/networks/DQN/network.py, cares_reinforcement_learning/networks/DoubleDQN/network.py, cares_reinforcement_learning/networks/DuelingDQN/network.py, cares_reinforcement_learning/networks/MAPERSAC/actor.py, cares_reinforcement_learning/networks/NaSATD3/actor.py, cares_reinforcement_learning/networks/NaSATD3/critic.py, cares_reinforcement_learning/util/configurations.py, cares_reinforcement_learning/util/network_factory.py
new key word for algorithm parameters
e.g. TD3 --hidden_size 1024 1024
This will set the hidden size to 1024 over the default 256
=> Parameter overrides for default Hidden Size

README.md, cares_reinforcement_learning/util/configurations.py, cares_reinforcement_learning/util/helpers.py, cares_reinforcement_learning/util/record.py
This adds a log path to the training config. This default makes new [changes](https://github.com/UoA-CARES/gymnasium_envrionments/pull/54) in GymEnv mimic previous behaviour
=> Added log path to default training config

.github/workflows/autoformatting.yml, cares_reinforcement_learning/util/record.py
Added model saving when the system reaches a new best
=> Saves models when training data outperforms previous

cares_reinforcement_learning/util/rl_parser.py
Config now just takes a data path parameter and loads the configuration files within
=> Config Load

cares_reinforcement_learning/networks/CTD4/critic.py, cares_reinforcement_learning/networks/CrossQ/actor.py, cares_reinforcement_learning/networks/CrossQ/critic.py, cares_reinforcement_learning/networks/DDPG/actor.py, cares_reinforcement_learning/networks/DDPG/critic.py, cares_reinforcement_learning/networks/DroQ/critic.py, cares_reinforcement_learning/networks/DuelingDQN/network.py, cares_reinforcement_learning/networks/MAPERSAC/critic.py, cares_reinforcement_learning/networks/MAPERTD3/critic.py, cares_reinforcement_learning/networks/RDSAC/critic.py, cares_reinforcement_learning/networks/RDTD3/critic.py, cares_reinforcement_learning/networks/REDQ/critic.py, cares_reinforcement_learning/networks/SAC/actor.py, cares_reinforcement_learning/networks/SAC/critic.py, cares_reinforcement_learning/networks/SACD/actor.py, cares_reinforcement_learning/networks/TD3/actor.py, cares_reinforcement_learning/networks/TD3/critic.py, cares_reinforcement_learning/networks/TQC/critic.py, cares_reinforcement_learning/networks/common.py, cares_reinforcement_learning/util/configurations.py
Overhaul to the MLP class and configurations to simplify while also enabling greater flexibility in the creation of entirely custom networks
=> MLP Config Update

cares_reinforcement_learning/util/record.py
=> MemoryBuffer can be updated in Record - recording turn on and off

cares_reinforcement_learning/algorithm/policy/CTD4.py, cares_reinforcement_learning/algorithm/policy/MAPERSAC.py, cares_reinforcement_learning/algorithm/policy/MAPERTD3.py, cares_reinforcement_learning/algorithm/policy/RDSAC.py, cares_reinforcement_learning/algorithm/policy/RDTD3.py, cares_reinforcement_learning/algorithm/policy/REDQ.py, cares_reinforcement_learning/algorithm/policy/TQC.py, tests/algorithms/test_algorithms.py
… - new tests for calculate value
=> Fix Calculate Value 

cares_reinforcement_learning/memory/memory_buffer.py
=> Memory Save Protection

cares_reinforcement_learning/util/configurations.py, cares_reinforcement_learning/util/record.py
Can now set: --checkpoint_interval NUM_EPISODES to delay the saving of the csv files, will see performance gains for tasks with very low steps per episode - e.g. space_gym
=> Logging Delay
